'use client';
import { useEffect, useRef, useState } from 'react';
import { money, samples } from './model';
import { jobs, modeLabels, operatingData, stock, workItems, type BusinessMode } from './erp-model';
type Activity={id:number;title:string;detail:string;time:string};
const periods:Record<string,string>={q3:'Jul–Sep 2026',q2:'Apr–Jun 2026',all:'Apr–Sep 2026'};
function Trend({values,labels,compact=false}:{values:number[];labels?:string[];compact?:boolean}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;function draw(){if(!canvas)return;const c=canvas.getContext('2d');if(!c)return;const w=canvas.clientWidth,h=canvas.clientHeight,d=Math.min(window.devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;c.scale(d,d);const left=compact?2:48,right=compact?2:14,top=compact?5:16,bottom=compact?4:29;const max=Math.max(...values,1)*1.15;const x=(i:number)=>left+i*(w-left-right)/Math.max(values.length-1,1);const y=(v:number)=>h-bottom-v/max*(h-top-bottom);if(!compact){c.font='10px Arial';c.fillStyle='#92a2b8';for(let i=0;i<4;i++){const v=max*i/3,yy=y(v);c.strokeStyle='#223041';c.lineWidth=1;c.beginPath();c.moveTo(left,yy);c.lineTo(w-right,yy);c.stroke();c.fillText('$'+Math.round(v/100000)+'k',1,yy+3)}labels?.forEach((l,i)=>{c.textAlign='center';c.fillText(l,x(i),h-8)});}c.beginPath();values.forEach((v,i)=>i?c.lineTo(x(i),y(v)):c.moveTo(x(i),y(v)));c.strokeStyle='#58a6ff';c.lineWidth=compact?1.7:2.5;c.stroke();if(!compact){c.lineTo(x(values.length-1),h-bottom);c.lineTo(x(0),h-bottom);c.closePath();c.fillStyle='#58a6ff0b';c.fill();values.forEach((v,i)=>{c.beginPath();c.arc(x(i),y(v),3,0,Math.PI*2);c.fillStyle='#58a6ff';c.fill()});}}
 draw();const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect();},[values,labels,compact]);
 return <canvas ref={ref} className={compact?'erp-spark':'erp-trend'} aria-hidden="true"/>;
}
export function ErpOverview({period,onPeriod,approvedIds,onReceipt,disabled,events,onActivity,mode,onMode}:{mode:BusinessMode;onMode:(mode:BusinessMode)=>void;period:string;onPeriod:(v:string)=>void;approvedIds:string[];onReceipt:(id:string)=>void;disabled:boolean;events:Activity[];onActivity:(title:string,detail:string)=>void}){
 const [completed,setCompleted]=useState<string[]>([]),[purchases,setPurchases]=useState<string[]>([]),[query,setQuery]=useState(''),[message,setMessage]=useState('');
 const data=operatingData(period,mode),queue=workItems.filter(w=>mode==='combined'||w.type===mode),filtered=queue.filter(w=>(w.id+' '+w.customer+' '+w.item).toLowerCase().includes(query.toLowerCase()));
 const pending=samples.filter(r=>!approvedIds.includes(r.id));
 const revenue=data.rows.map(m=>m.revenue),profit=data.rows.map(m=>m.revenue-m.expenses),margin=data.profit/data.revenue*100;
 const revenueMix=mode==='service'?[['Implementation',.48],['Retainers',.32],['Advisory',.20]] as const:mode==='product'?[['Workstation bundles',.45],['Sensor kits',.35],['Network hubs',.20]] as const:[['Service delivery',.60],['Product sales',.40]] as const;
 const sampleActivity=mode==='service'?[['Job JOB-1048 updated','18 of 25 tasks complete · Operations'],['Proposal ready for review','Coastal Partners · CRM']]:mode==='product'?[['Order ORD-2086 created','Workstation bundle × 4 · Sales'],['Stock threshold reached','Sensor kit · Inventory']]:[['Job JOB-1048 updated','Acacia Creative · Operations'],['Order ORD-2086 created','Summit Supplies · Sales'],['Stock threshold reached','Sensor kit · Inventory']];
 return <div className="erp-overview">
 <div className="erp-toolbar"><div className="erp-mode" role="group" aria-label="Business type">{(Object.keys(modeLabels) as BusinessMode[]).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>onMode(m)} disabled={disabled}>{m==='combined'?'Combined':m==='service'?'Services':'Products'}</button>)}</div><span className="erp-data-tag">Sample data · AUD</span><label><span className="sr-only">Overview reporting period</span><select value={period} disabled={disabled} onChange={e=>onPeriod(e.target.value)}>{Object.entries(periods).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
 <div className="erp-kpis"><article><span>Total revenue</span><strong>{money(data.revenue)}</strong><small>{modeLabels[mode]} · {periods[period]}</small><Trend values={revenue} compact/></article><article><span>Operating expenses</span><strong>{money(data.expenses)}</strong><small>Sample finance records</small><Trend values={data.rows.map(m=>m.expenses)} compact/></article><article><span>Operating profit</span><strong>{money(data.profit)}</strong><small>{margin.toFixed(1)}% operating margin</small><Trend values={profit} compact/></article><article><span>{mode==='product'?'Open orders':mode==='service'?'Active jobs':'Open jobs & orders'}</span><strong>{queue.filter(w=>!completed.includes(w.id)).length.toString().padStart(2,'0')}</strong><small>September sample work queue</small><div className="erp-queue-kpi"><i/><span>{pending.length} receipts awaiting review</span></div></article></div>
 <div className="erp-grid"><section className="erp-panel sales-panel" id="sales"><div className="erp-panel-title"><h2>Revenue overview</h2><span>{periods[period]}</span></div><p className="erp-caption">{modeLabels[mode]} · Sample revenue in AUD</p><Trend values={revenue} labels={data.rows.map(m=>m.label.slice(0,3))}/><details className="erp-figures"><summary>View financial figures</summary><div className="table-scroll"><table><caption className="sr-only">Financial figures for selected business type</caption><thead><tr><th>Month</th><th>Revenue</th><th>Expenses</th><th>Profit</th></tr></thead><tbody>{data.rows.map(m=><tr key={m.label}><th scope="row">{m.label}</th><td>{money(m.revenue)}</td><td>{money(m.expenses)}</td><td>{money(m.revenue-m.expenses)}</td></tr>)}</tbody></table></div></details></section>
 <section className="erp-panel"><div className="erp-panel-title"><h2>{mode==='combined'?'Revenue by business line':mode==='service'?'Service revenue mix':'Product revenue mix'}</h2><span>By revenue</span></div><p className="erp-caption">Illustrative breakdown · {periods[period]}</p><div className="erp-rankings">{revenueMix.map(([label,fraction])=><div key={label}><div><span>{label}</span><strong>{money(Math.round(data.revenue*fraction))}</strong></div><div className="erp-meter"><i style={{width:`${fraction*100}%`}}/></div></div>)}</div><div className="erp-panel-note">{mode==='combined'?'One view across client services and product sales. Switch business type to explore each side.':'Your production categories would come from your own services, product catalogue, and accounting records.'}</div></section>
 <section className="erp-panel erp-work" id="work"><div className="erp-panel-title"><h2>{mode==='combined'?'Recent jobs & orders':mode==='service'?'Client jobs':'Customer orders'}</h2><span>September sample queue</span></div><label className="erp-search"><span className="sr-only">Search jobs and orders</span><input type="search" placeholder="Search customer, reference or work…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="table-scroll"><table><caption className="sr-only">Recent sample jobs and orders</caption><thead><tr><th>Reference / customer</th><th>Value</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map(w=><tr key={w.id}><th scope="row"><strong>{w.id}</strong><small>{w.customer}</small><small>{w.item}</small></th><td>{money(w.amount)}</td><td><span className={`erp-badge ${completed.includes(w.id)?'done':''}`}>{completed.includes(w.id)?w.done:w.status}</span></td><td><button className="erp-inline" disabled={disabled||completed.includes(w.id)} onClick={()=>{setCompleted(p=>[...p,w.id]);onActivity(`${w.type==='service'?'Job':'Order'} ${w.id} ${w.done.toLowerCase()}`,`${w.customer} · demo action only`);setMessage(`${w.id} ${w.done.toLowerCase()} in this session. No external system was updated.`)}}>{completed.includes(w.id)?'Done ✓':w.next}</button></td></tr>)}</tbody></table>{filtered.length===0&&<p className="erp-empty">No matching jobs or orders. Try a customer name or reference.</p>}</div><p className="erp-panel-note">Queue items are examples, not the complete ledger behind the revenue chart.</p></section>
 <section className="erp-panel" id="activity"><div className="erp-panel-title"><h2>Activity feed</h2><span>All business actions</span></div><div className="erp-feed" aria-live="polite">{events.map(e=><div key={e.id}><span className="erp-feed-icon">✓</span><div><strong>{e.title}</strong><p>{e.detail}</p></div><time>{e.time}</time></div>)}{sampleActivity.map(([title,detail])=><div key={title}><span className="erp-feed-icon">◇</span><div><strong>{title}</strong><p>{detail}</p></div><span className="erp-feed-time">Sample</span></div>)}</div><p className="erp-panel-note">New demo actions appear here. A production feed would show supported events from your connected systems.</p></section>
 {mode!=='product'&&<section className="erp-panel" id="service-work"><div className="erp-panel-title"><h2>Service delivery</h2><span>Sample project progress</span></div><div className="erp-delivery">{jobs.map(j=><div key={j.name}><div><strong>{j.name}</strong><span>{j.progress}%</span></div><small>{j.client} · {j.detail}</small><div className="erp-meter"><i style={{width:`${j.progress}%`}}/></div></div>)}</div><p className="erp-panel-note">Task progress illustrates a project-tool connection. Demo job approvals above do not edit these sample tasks.</p></section>}
 {mode!=='service'&&<section className="erp-panel" id="inventory"><div className="erp-panel-title"><h2>Inventory & purchasing</h2><span>Sample stock snapshot</span></div><div className="erp-stock">{stock.map(s=><div key={s.sku}><div><strong>{s.name}</strong><small>{s.sku} · Reorder below {s.reorder}</small></div><span className={s.onHand<s.reorder?'erp-low-stock':''}>{s.onHand} units</span><button className="erp-inline" disabled={disabled||purchases.includes(s.sku)} onClick={()=>{setPurchases(p=>[...p,s.sku]);onActivity('Purchase request drafted',`${s.name} · pending approval · demo only`);setMessage(`Draft purchase request created for ${s.name}. Nothing has been ordered.`)}}>{purchases.includes(s.sku)?'Drafted ✓':'Draft request'}</button></div>)}</div><p className="erp-panel-note">Draft requests are recorded in the activity feed. No supplier orders are placed.</p></section>}
 </div><p className="erp-action-notice" role="status">{message}</p>
 <section className="erp-source-strip"><div><h2>Your connected workspace</h2><p>Example connections · none are live in this demo</p></div><div className="erp-source-tags"><span>Accounting</span><span>CRM</span><span>Projects</span><span>E-commerce</span><span>Inventory</span><span>Documents</span></div><a href="#connections">How it connects ↗</a></section>
 <section className="erp-approvals"><div className="erp-panel-title"><h2>Receipt approvals <span className="erp-count">{pending.length}</span></h2><span>September sample queue</span></div><div>{pending.map(r=><button key={r.id} disabled={disabled} onClick={()=>onReceipt(r.id)}><span>{r.vendor}</span><strong>{money(r.total)}</strong><span>Review ↗</span></button>)}{pending.length===0&&<p>All sample receipts approved.</p>}</div></section>
 </div>;
}
