import type { Metadata } from 'next';
import './showcase.css';
import BrandLogo from '../brand-logo';
export const dynamic = 'force-static';
export const metadata: Metadata = {title:'Dashboard showcase | ZoneSeven',description:'A glimpse of your business, connected. Bespoke dashboard concepts for service and product businesses, built around your data and tools.'};
function Preview({image,alt,label,priority=false}:{image:string;alt:string;label:string;priority?:boolean}){return <figure className="sc-preview"><div className="sc-frame"><span aria-hidden="true">● ● ●</span><span>{label}</span><span>CONCEPT PREVIEW</span></div><img src={`/showcase/${image}.png`} alt={alt} width={845} height={777} loading={priority?'eager':'lazy'}/><figcaption>Illustrative screenshot · sample business data</figcaption></figure>}
export default function Page(){return <div className="showcase">
<a className="skip" href="#showcase-main">Skip to content</a><header className="sc-nav"><a href="/" className="brand-home" aria-label="ZoneSeven home"><BrandLogo/></a><a href="/#contact">Let’s talk ↗</a></header>
<main id="showcase-main">
<section className="sc-intro"><p className="sc-kicker">BESPOKE BUSINESS DASHBOARDS / A FIRST LOOK</p><h1>All your tools.<br/><span>One operational view.</span></h1><div className="sc-intro-bottom"><p>Connect your tools to get one operational view of your business. Your data, your workflows, your priorities — together in a dashboard built around you.</p><a className="sc-cta" href="/#contact">Imagine this for your business <span aria-hidden="true">↗</span></a></div></section>
<section className="sc-integrations" aria-labelledby="tools-title"><div><p className="sc-kicker">FAMILIAR TOOLS. ONE CONNECTED PICTURE.</p><h2 id="tools-title">Your tools belong together.</h2><p>A bespoke dashboard can bring information from the systems your business already uses into one clear view.</p></div><div className="sc-logo-grid">{[['xero','Xero','Accounting','#13b5ea'],['quickbooks','QuickBooks','Bookkeeping','#2ca01c'],['shopify','Shopify','Ecommerce','#659b38'],['stripe','Stripe','Payments','#635bff'],['hubspot','HubSpot','Customer relationships','#e96d43'],['asana','Asana','Projects & tasks','#ed6379']].map(([id,name,category,color])=><div className="sc-tool" key={id}><span style={{backgroundColor:color,maskImage:`url(/logos/${id}.svg)`,WebkitMaskImage:`url(/logos/${id}.svg)`}} aria-hidden="true"/><div><strong>{name}</strong><small>{category}</small></div></div>)}</div><p className="sc-integration-note">Example systems for a tailored build. Connections depend on each tool’s API, permissions and your setup; none are live in this showcase.</p></section>
<section className="sc-feature" aria-labelledby="overview-title"><div className="sc-feature-copy"><p className="sc-kicker">01 / THE BIG PICTURE</p><h2 id="overview-title">Your business.<br/>At a glance.</h2><p>A single place to see performance, follow work and understand what needs attention. Designed for businesses selling services, products, or both.</p><ul><li>Revenue, costs & performance</li><li>Customers, jobs & orders</li><li>Activity across your connected tools</li><li>Custom built automation workflows</li></ul><p className="sc-note">A preview of what’s possible. These are static images, using sample data.</p></div><Preview image="combined" alt="Concept dashboard showing combined business revenue, operating expenses, profit and work in progress in a dark interface." label="Business overview" priority/></section>
<section className="sc-scenarios" aria-labelledby="scenarios-title"><div className="sc-workflow-intro"><div className="sc-workflow-copy"><p className="sc-kicker">02 / BUILT AROUND HOW YOU WORK</p><h2 id="scenarios-title">Your dashboard.<br/><span>Your way of working.</span></h2><p className="sc-workflow-lead">Choose what you see. Connect the tools you use. Automate the work that slows you down.</p><p className="sc-workflow-body">We tailor your dashboard to your team’s roles, priorities and approval rules, so it fits the way your business operates.</p></div><div className="sc-workflow-benefits"><p className="sc-kicker">TAILORED TO YOUR BUSINESS</p><ul><li>Custom views, metrics and reports</li><li>Connections to your existing business tools</li><li>Custom built automation workflows</li></ul></div></div><div className="sc-process-cards">
{[
{kind:'invoice',title:'Invoice automation',intro:'From incoming invoice to an approved accounting entry.',steps:[['Capture the invoice','Receive invoices from your inbox or uploads and extract supplier details, line items and totals.'],['Check and route','Match against purchase orders, flag duplicates or discrepancies and send exceptions to the right person.'],['Approve and record','Apply your approval rules, then update your accounting system with an audit trail.']],documentTitle:'Invoice review',ref:'INV-2048 · Summit Supplies',rows:[['Purchase order','PO-1082 · Matched'],['Subtotal','$2,400.00'],['GST (10%)','$240.00'],['Total','$2,640.00']],status:'Ready for approval',note:'Example rule: invoices over $2,000 require manager approval.'},
{kind:'quote',title:'Quote generation',intro:'Turn an enquiry into a quote that looks and sounds like you.',steps:[['Start with the enquiry','Bring customer details and requirements in from your CRM, enquiry form or team.'],['Build your branded quote','Use your catalogue, rates and pricing rules to prepare line items, terms and a branded draft.'],['Review and send','Route the quote for review, then send it through your chosen system and track its status.']],documentTitle:'Project quote',ref:'QT-0316 · Prepared for Cedar Co.',rows:[['Discovery & planning','$850.00'],['Implementation','$2,400.00'],['GST (10%)','$325.00'],['Quote total','$3,575.00']],status:'Draft for review',note:'Your logo, services, pricing and terms on every quote.'},
{kind:'report',title:'Time series reports',intro:'See what is changing, with reports delivered on your schedule.',steps:[['Connect your data','Bring together the finance, sales or operations data needed for your chosen metrics.'],['Compare performance','Track results over time, compare periods and highlight trends against your targets.'],['Schedule and share','Prepare a weekly or monthly report for the people who need it, with review steps where required.']],documentTitle:'Monthly performance',ref:'September 2026 · Revenue summary',rows:[['July','$42,800'],['August','$46,200'],['September','$51,600'],['Change vs August','+11.7%']],status:'Scheduled monthly',note:'Example schedule: prepare a report on the first day of each month.'}
].map((card,i)=><details className="sc-process-card" key={card.kind}><summary><span className={`sc-workflow-icon sc-workflow-icon--${card.kind}`} aria-hidden="true"><i/><i/><i/></span><span className="sc-process-index">0{i+1} / CUSTOM WORKFLOW</span><span className="sc-process-title">{card.title}</span><span className="sc-process-intro">{card.intro}</span><span className="sc-process-toggle"><span className="sc-when-closed">See how it works</span><span className="sc-when-open">Hide process</span><span className="sc-chevron" aria-hidden="true">⌄</span></span></summary><div className="sc-process-content"><ol>{card.steps.map(([title,text],step)=><li key={title}><span>{step+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><div className="sc-business-example"><div className="sc-example-brand"><span className="sc-brand-mark" aria-hidden="true">n.</span><div>NORTHLINE<small>BUSINESS SOLUTIONS</small></div></div><p className="sc-example-label">YOUR BRANDED WORKSPACE</p><h4>{card.documentTitle}</h4><p className="sc-example-ref">{card.ref}</p><dl>{card.rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><span className="sc-example-status">{card.status}</span><p className="sc-example-note">{card.note}</p></div><p className="sc-example-disclaimer">Fictional business · illustrative process and data</p></div></details>)}
</div></section>
<section className="sc-connect" aria-labelledby="connect-title"><div><p className="sc-kicker">03 / YOUR SYSTEMS, CONNECTED</p><h2 id="connect-title">Built on your data.<br/>Made for your business.</h2><p>We design the dashboard around the tools you already use, the information you need and the actions that matter to your team.</p></div><ol><li><span>01</span><div><h3>Connect the tools you use.</h3><p>Your accounting, CRM, ecommerce and job management systems connect through supported APIs, secure connectors or scheduled data imports.</p></div></li><li><span>02</span><div><h3>Bring the right data together.</h3><p>We match records across systems and shape a shared view of your customers, finances and operations. Access and refresh schedules are tailored to your business.</p></div></li><li><span>03</span><div><h3>Make your next action clear.</h3><p>A bespoke build can generate reports, prepare invoices and process receipts, with approvals and an activity history. Available actions depend on your connected systems.</p></div></li></ol></section>
<section className="sc-end"><p className="sc-kicker">YOUR BUSINESS COULD LOOK LIKE THIS.</p><h2>Let’s bring it<br/>all together.</h2><a className="sc-cta" href="/#contact">Talk about your dashboard <span aria-hidden="true">↗</span></a><p>Built around your business. Connected to your tools.</p></section>
</main><footer className="sc-footer"><a href="/" className="brand-home" aria-label="ZoneSeven home"><BrandLogo/></a><a href="/">AI & automation · Websites · Marketing ↗</a></footer></div>}
